##########################################################
##########################################################
## 
## 1). TaskTide Global Configurations
## 
##########################################################
##########################################################

# Which client to run
tasktide.client=web-api


# Collection Paramenters
tasktide.core.collection.workflow.name=profiled-workflow
tasktide.core.collection.step.name=profiled-step
tasktide.core.collection.workitem.name=profiled-work-item


# Repository parameters
tasktide.core.repository.type=nosql
tasktide.core.repository.file-path=tasktideItemStore


# Jakarta NoSQL parameters
tasktide.core.repository.jnosql.type=document
tasktide.core.repository.jnosql.provider=couchDB
tasktide.core.repository.jnosql.provider-class=org.eclipse.jnosql.databases.couchdb.communication.CouchDBDocumentConfiguration
tasktide.core.repository.jnosql.user=admin
tasktide.core.repository.jnosql.password=password
tasktide.core.repository.jnosql.host=localhost:59484


# Utility parameters
tasktide.utils.date-format=dd/MM/yy HH:mm:ss
tasktide.utils.token-expiration-days=4


##########################################################
##########################################################
## 
## 3). TaskTide Engine Configurations
## 
##########################################################
##########################################################


# Task Tide Engine Parameters
tasktide.engine.worker.lock-wait-time=4


# Time Keeper Observer
tasktide.engine.observer.timekeeper.level=1
tasktide.engine.observer.timekeeper.onStart.canFail=true
tasktide.engine.observer.timekeeper.onProcessing.canFail=true
tasktide.engine.observer.timekeeper.onPEnd.canFail=true
tasktide.engine.observer.timekeeper.waitTime=1000000



##########################################################
##########################################################
## 
## 4). Jakarta NoSQL 
## 
## Reference Configs GitHub:
##   jnosql-databases.git
##  
##########################################################
##########################################################


# Jakarta NoSQL config
jnosql.document.provider=org.eclipse.jnosql.databases.couchdb.communication.CouchDBDocumentConfiguration
jnosql.document.database=tasktide_database
jnosql.couchdb.host=couchDB
jnosql.couchdb.username=admin
jnosql.couchdb.password=password
jnosql.couchdb.port=5984