##########################################################
##########################################################
## 
## 1). TaskTide Global Configurations
## 
##########################################################
##########################################################

# Which client to run
tasktide.client=web-api


# Repository parameters
tasktide.core.repository.type=sql
tasktide.core.repository.jnosql.type=mysql


# Result set size limit
tasktide.core.results-set-size=30


# ItemStore config
# tasktide.core.repository.type=sqlite
# tasktide.core.repository.file-path=sqliteDbStore

# Mutex parameters in milliseconds
tasktide.mutex.maxRandomDuration=500L
tasktide.mutex.minRandomDuration=10L
tasktide.mutex.staleFileThreshold=500L
tasktide.mutex.startJitter=20L
tasktide.mutex.endJitter=20L
tasktide.mutex.retryInterva=30L


# Utility parameters
tasktide.utils.date-format=dd/MM/yy HH:mm:ss
tasktide.utils.token-expiration-days=4



##########################################################
##########################################################
## 
## 3). TaskTide Engine Configurations
## 
##########################################################
##########################################################


# Engine execution policy
tasktide.engine.execution-policy=batch


# Log stream path
tasktide.engine.process-executor.stream-directory=./


# Acquisition policy parameters
tasktide.engine.policy.acquisition.iteration-limit=-1
tasktide.engine.policy.acquisition.should-cycle=false


# Workflow parameters
tasktide.engine.policy.acquisition.workflow.strategy=Sequential
tasktide.engine.policy.acquisition.workflow.mode=Exhaust


# Task Tide Engine Parameters
tasktide.engine.worker.window-size=10
tasktide.engine.worker.lock-wait-time=4


# Parallelism
tasktide.engine.worker.threads.worker-pool-size=1
tasktide.engine.worker.threads.itemtask=1


# Time Keeper Observer
tasktide.engine.observer.timekeeper.level=1
tasktide.engine.observer.timekeeper.onStart.canFail=true
tasktide.engine.observer.timekeeper.onProcessing.canFail=true
tasktide.engine.observer.timekeeper.onPEnd.canFail=true
tasktide.engine.observer.timekeeper.waitTime=1000000



##########################################################
##########################################################
## 
## 4). Jakarta NoSQL 
## 
## Reference Configs GitHub:
##   jnosql-databases.git
##  
##########################################################
##########################################################


# Jakarta NoSQL config
jnosql.document.provider=org.eclipse.jnosql.databases.couchdb.communication.CouchDBDocumentConfiguration
jnosql.document.database=tasktide_database
jnosql.couchdb.host=couchDB
jnosql.couchdb.username=admin
jnosql.couchdb.password=password
jnosql.couchdb.port=5984



##########################################################
##########################################################
##  
## 5). JPA Config
##  
## References:
##  https://www.jetbrains.com/datagrip/jdbc-drivers/#
##  
##########################################################
##########################################################


# JDBC config: Must create database
datasource.url=jdbc:mysql://maria_db:3306/tasktide
datasource.user=root
datasource.password=password
datasource.driver=com.mysql.cj.jdbc.Driver


# Hibernate config
hibernate.dialect=org.hibernate.dialect.MariaDBDialect
hibernate.hbm2ddl.auto=update



##########################################################
##########################################################
## 
## 6). TaskTide REST-API 
## 
## https://eclipse-ee4j.github.io/jersey/
## https://jakarta.ee/specifications/restful-ws/
## 
##########################################################
##########################################################


# Base web service settings
tasktide.web-api.host=http://localhost
tasktide.web-api.port=8080
tasktide.web-api.base-path=/tasktide