#########################################################################
#########################################################################
##
## Configuration for TaskTide-Engine Deployment with CouchDB backend
##
#########################################################################
#########################################################################


#######################################
#######################################
## 
## 1). Global Configs
## 
#######################################
#######################################


# Component networks
networks:
  dbNet:

  tasktide_web:

  tasktide_engine:

  nginx_alb:

secrets:
  couchDbPass:
    file: ./couchDB-pass.txt



#############################################
#############################################
## 
## 2). Application Proxy
## 
#############################################
#############################################
services:


# nginx
  nginx_alb:
    image: nginx:1.27-alpine
    container_name: tasktide_app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx_alb
      - tasktide_web

    depends_on:
      - tasktide_webapi

    deploy:
      replicas: 1



#############################################
#############################################
## 
## 3). CouchDB Service
## 
#############################################
#############################################


# CouchDB
  couchDB:
    container_name: "couchdb"
    image: "couchdb:2.3.1"
    
    networks:
      - dbNet

    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password

    ports:
      - "5984:5984"

    volumes:
      - ./couchdb_data:/opt/couchdb/data

    secrets:
      - couchDbPass
    
    deploy:
      replicas: 1


# Creates database admin:password
  initCouchDB:
    image: ubuntu:24.04
    networks:
      - dbNet
    volumes:
      - ./configDB.sh:/opt/configDB.sh:ro
      - ./indexes.json:/opt/indexes.json:ro
    entrypoint: [ "/bin/bash", "/opt/configDB.sh" ]
    secrets:
      - couchDbPass
    depends_on:
      - couchDB



#############################################
#############################################
## 
## 4). TaskTide Web API
## 
#############################################
#############################################


# Spins-up 3 web apps
  tasktide_webapi:
    image: tasktide:latest
    networks:
      - tasktide_web
      - dbNet

    volumes:
      - ./microprofile-config.properties:/opt/tasktide/config/META-INF/microprofile-config.properties

    working_dir: /opt/tasktide

    command:
        - web-api
        - --host
        - "tasktide_webapi"
        - --port
        - "80"
        - --base-path
        - "/tasktide"

    deploy:
      replicas: 3

    depends_on:
      - initCouchDB



#############################################
#############################################
## 
## 5). TaskTide Engine
## 
#############################################
#############################################


# Spins-up 3 web apps: mario_traine
  mario_ai_agent:
    image: bkenna/tasktide:apptainer

    cap_add:
      - SYS_ADMIN

    security_opt:
      - no-new-privileges:true

    devices:
      - /dev/fuse

    networks:
      - nginx_alb
      - dbNet

    volumes:
      - ./microprofile-config.properties:/opt/tasktide/config/META-INF/microprofile-config.properties
      - ./tasktide_data:/opt/tasktide/tasktide-process-executor-streams
      - ../sif/mario-agent.sif:/opt/mario-agent/mario-agent.sif:ro
      - ./mario-data/:/data/mario:rw

    working_dir: /opt/tasktide

    command:
        - engine
        - --repository-type
        - "nosql"
        - --target
        - "WORKITEM"
        - --step-name
        - "TrainMarioBros,PlayMarioBros"
        - --execution-policy
        - "service"
        - --worker-pool-size
        - "2"
        - --worker-window-size
        - "4"
        - --item-task-threads
        - "2"
        - "--result-set-size"
        - "2"
        - "--acquisition-mode"
        - "SCANNER"
        - "--strategy-type"
        - "ROUND_ROBIN"

    deploy:
      replicas: 3

    depends_on:
      - nginx_alb