events {}

http {

    upstream tasktide_backend {
        server tasktide_webapi:80;
        zone tasktide_backend 64k;
    }

    server {
        listen 80;

        location /services/ {
            proxy_pass http://tasktide_backend/tasktide/api/services/;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}