#!/bin/bash

: << 'COMMENT'

Database validation:
  1). The SQLite database is stored beside its md5sum file
  2). Allows queried version to checked against life version
  3). Allows queried version to be verified as an approved source

Record validation:
  1). Queries each signature and record hash field.
  2). Verifies the integrity of queried record hash against the stored record.
  3). Fetches the PASSKEY GH secret (lets keep passgen.py for now)
  4). Checks that the queried record was generated by a verified source.


Fields
- Record id is auto-incremented     - only ever a single thread writing
- Record Signature Field            - PASSKEY is a GH secret, lets keep with passgen.py for now
- Record has a Record Hash Field    - As shown
- Data field is below
{
  "name": "My Use Case",
  "description": "Short description of what this use case demonstrates.",
  "status": "active",
  "category": "example",
  "repository": "BrenKenna/TaskTide-UseCases",
  "path": "MyUseCase"
}

COMMENT



# Generate an entry signature
PASSKEY=$(python .secret/passgen.py --password-length 32 --amount 12 | sort -R | cut -f 2)
TIME_STAMP=$(date +%s%3N)
UUID=$(uuidgen)
REPO_NAME="New Repository Record"
RECORD_PAYLOAD="{ 'Some': 'JSON Data' }"
RECORD_HASH=$(echo "$TIME_STAMP - $UUID - $REPO_NAME - $RECORD_PAYLOAD" | md5sum - | awk '{print $1}')
RECORD_SIGNATURE=$(echo "$RECORD_HASH" | openssl dgst -sha384 -hmac "$PASSKEY" | awk '{ print $2 }')


# 1). Evaluates the integrity of the queried record against stored
HASH_EVAL=$(echo "$TIME_STAMP - $UUID - $REPO_NAME - $RECORD_PAYLOAD" | md5sum - | awk '{print $1}')
if [ $RECORD_HASH != $HASH_EVAL ]
then
  echo "Record '$RECORD_HASH' for '$REPO_NAME' not validated: Fails hash validation"
else
  echo "Record '$RECORD_HASH' for '$REPO_NAME' is valid"
fi


# 2). Evaulates that queried record was generated by verified source using record signature
RECORD_EVAL=$(echo "$RECORD_HASH" | openssl dgst -sha384 -hmac "$PASSKEY" | awk '{ print $2 }')
if [ $RECORD_SIGNATURE != $RECORD_EVAL ]
then
  echo "Record '$RECORD_HASH' for '$REPO_NAME' not validated: Fails signature validation"
else
  echo "Record '$RECORD_HASH' for '$REPO_NAME' is valid"
fi



# Initialize repo DB
sqlite3 tasktide-use-case-registry.db <<'EOF'

CREATE TABLE use_cases(
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  UUID TEXT NOT NULL UNIQUE,
  Repo_Url TEXT NOT NULL UNIQUE,
  Record_Name TEXT NOT NULL,
  Record_Created_At INTEGER NOT NULL,
  Record_Hash TEXT NOT NULL UNIQUE,
  Record_Signature TEXT NOT NULL,
  Payload JSON NOT NULL
);

EOF


#####################################
#####################################
##
## 1). Bioninformatic Workflows
##
######################################
######################################


# Define record
PASSKEY=$(cat ../.secret/passkey)
TIME_STAMP=$(date +%s%3N)
UUID=$(uuidgen)
REPO_NAME="Bioinformatic Workflows"
REPO_URL="https://use-cases.tasktide.org/BioinformaticWorkflows"

RECORD_PAYLOAD=$(jq -cn \
  --arg name "Bioinformatic Workflows" \
  --arg description "A collection of shell scripts for exome/genome sequence alignment and downstream processing." \
  --arg type "core" \
  --arg status "active" \
  --arg repository "https://use-cases.tasktide.org/BioinformaticWorkflows" \
  --arg path "/BioinformaticWorkflows" \
    '{
      name: $name,
      description: $description,
      type: $type,
      status: $status,
      repository: $repository,
      path: $path
    }'
)


# Generate reference md5sum, and signature
RECORD_HASH=$(echo "$TIME_STAMP - $UUID - $REPO_NAME - $RECORD_PAYLOAD" | md5sum - | awk '{print $1}')
RECORD_SIGNATURE=$(echo "$RECORD_HASH" | openssl dgst -sha384 -hmac "$PASSKEY" | awk '{ print $2 }')


# Import record
sqlite3 tasktide-use-case-registry.db <<EOF

.parameter set :uuid 				'$UUID'
.parameter set :repoUrl 			'$REPO_URL'
.parameter set :repoName 			'$REPO_NAME'
.parameter set :timestamp 			'$TIMESTEP'
.parameter set :recordHash			'$RECORD_HASH'
.parameter set :recordSignature		'$RECORD_SIGNATURE'
.parameter set :recordPayload		'$RECORD_PAYLOAD'

INSERT INTO use_cases (
	UUID, Repo_Url,
	Record_Name, Record_Created_At,
	Record_Hash, Record_Signature,
	Payload
)

VALUES (
	:uuid, :repoUrl,
	:repoName, :timestamp,
	:recordHash, :recordSignature,
	:recordPayload
);

EOF


# Fetch record
sqlite3 tasktide-use-case-registry.db <<EOF

.headers on
.separator "\t"
.parameter set :repoName	'$REPO_NAME'

SELECT * FROM use_cases WHERE Record_Name = :repoName;

EOF

'''

Id      UUID    Repo_Url        Record_Name     Record_Created_At       Record_Hash     Record_Signature        Payload
1       0f311ce1-c779-4af2-be5a-ef3afe9b03d9            Bioinformatic Workflows         81c493f6c4da01bd3f5f5d505863a436        5543a7cda5fce11de2f305774c121bf1c4dea73b199dd41764201c97b94a2b2fcfc25df6747ebbbb6c21a1b0b6d56f16  {"name":"Bioinformatic Workflows","description":"A collection of shell scripts for exome/genome sequence alignment and downstream processing.","type":"core","status":"active","repository":"https://use-cases.tasktide.org/BioinformaticWorkflows","path":"/BioinformaticWorkflows"}

'''


#####################################
#####################################
##
## 2). Function Runner
##
######################################
######################################


# Define record
PASSKEY=$(cat ../.secret/passkey)
TIME_STAMP=$(date +%s%3N)
UUID=$(uuidgen)
REPO_NAME="Function Runner"
REPO_URL="https://use-cases.tasktide.org/FunctionRunner"

RECORD_PAYLOAD=$(jq -cn \
  --arg name "$REPO_NAME" \
  --arg description "Julia package for function definition, and parameter SerDe for defining in one environment and exeuction in another" \
  --arg type "core" \
  --arg status "active" \
  --arg repository "$REPO_URL" \
  --arg path "/FunctionRunner" \
    '{
      name: $name,
      description: $description,
      type: $type,
      status: $status,
      repository: $repository,
      path: $path
    }'
)


# Generate reference md5sum, and signature
RECORD_HASH=$(echo "$TIME_STAMP - $UUID - $REPO_NAME - $RECORD_PAYLOAD" | md5sum - | awk '{print $1}')
RECORD_SIGNATURE=$(echo "$RECORD_HASH" | openssl dgst -sha384 -hmac "$PASSKEY" | awk '{ print $2 }')


# Import record
sqlite3 tasktide-use-case-registry.db <<EOF

.parameter set :uuid 				'$UUID'
.parameter set :repoUrl 			'$REPO_URL'
.parameter set :repoName 			'$REPO_NAME'
.parameter set :timestamp 			'$TIMESTEP'
.parameter set :recordHash			'$RECORD_HASH'
.parameter set :recordSignature		'$RECORD_SIGNATURE'
.parameter set :recordPayload		'$RECORD_PAYLOAD'

INSERT INTO use_cases (
	UUID, Repo_Url,
	Record_Name, Record_Created_At,
	Record_Hash, Record_Signature,
	Payload
)

VALUES (
	:uuid, :repoUrl,
	:repoName, :timestamp,
	:recordHash, :recordSignature,
	:recordPayload
);

EOF


# Fetch record
sqlite3 tasktide-use-case-registry.db <<EOF

.headers on
.separator "\t"
.parameter set :repoName	'$REPO_NAME'

SELECT * FROM use_cases WHERE Record_Name = :repoName;

EOF

'''

Id      UUID    Repo_Url        Record_Name     Record_Created_At       Record_Hash     Record_Signature        Payload
2       f2bbcc29-6623-4966-8c18-9f9d1ffa7d69    https://use-cases.tasktide.org/FunctionRunner   Function Runner         e2c9edb04e13648aea67571e66c1d6b4 1862f9d7d9f2c90b0a69c58a89783c5762d01516ffceb35b88c4cc090d9eff033bd17e2a2b2c29b5dad4c0ddd0b1edb3 {"name":"Function Runner","description":"Julia package for function definition, and parameter SerDe for defining in one environment and exeuction in another","type":"core","status":"active","repository":"https://use-cases.tasktide.org/FunctionRunner","path":"/FunctionRunner"}

'''


#####################################
#####################################
##
## 3). Image Analysis
##
######################################
######################################


# Define record
PASSKEY=$(cat ../.secret/passkey)
TIME_STAMP=$(date +%s%3N)
UUID=$(uuidgen)
REPO_NAME="Image Analysis"
REPO_URL="https://use-cases.tasktide.org/ImageAnalysis"

RECORD_PAYLOAD=$(jq -cn \
  --arg name "$REPO_NAME" \
  --arg description "SparkR for expressive SQL image generation, and stacking into HDFS compatible formats" \
  --arg type "core" \
  --arg status "active" \
  --arg repository "$REPO_URL" \
  --arg path "/ImageAnalysis" \
    '{
      name: $name,
      description: $description,
      type: $type,
      status: $status,
      repository: $repository,
      path: $path
    }'
)


# Generate reference md5sum, and signature
RECORD_HASH=$(echo "$TIME_STAMP - $UUID - $REPO_NAME - $RECORD_PAYLOAD" | md5sum - | awk '{print $1}')
RECORD_SIGNATURE=$(echo "$RECORD_HASH" | openssl dgst -sha384 -hmac "$PASSKEY" | awk '{ print $2 }')


# Import record
sqlite3 tasktide-use-case-registry.db <<EOF

.parameter set :uuid 				'$UUID'
.parameter set :repoUrl 			'$REPO_URL'
.parameter set :repoName 			'$REPO_NAME'
.parameter set :timestamp 			'$TIMESTEP'
.parameter set :recordHash			'$RECORD_HASH'
.parameter set :recordSignature		'$RECORD_SIGNATURE'
.parameter set :recordPayload		'$RECORD_PAYLOAD'

INSERT INTO use_cases (
	UUID, Repo_Url,
	Record_Name, Record_Created_At,
	Record_Hash, Record_Signature,
	Payload
)

VALUES (
	:uuid, :repoUrl,
	:repoName, :timestamp,
	:recordHash, :recordSignature,
	:recordPayload
);

EOF


# Fetch record
sqlite3 tasktide-use-case-registry.db <<EOF

.headers on
.separator "\t"
.parameter set :repoName	'$REPO_NAME'

SELECT * FROM use_cases WHERE Record_Name = :repoName;

EOF


'''

Id      UUID    Repo_Url        Record_Name     Record_Created_At       Record_Hash     Record_Signature        Payload
3       9df00807-031e-4538-8d69-82d3daf4dc87    https://use-cases.tasktide.org/ImageAnalysis    Image Analysis          1eedda3cae95c69ea623276fa35fda96 7c8906837a563fece6bb47fb3ad91a4cf59d0fd5533a0bcec5159f0f3b2a4035a0fd20632db4f06a0cd5c9ca208ee1ef {"name":"Image Analysis","description":"SparkR for expressive SQL image generation, and stacking into HDFS compatible formats","type":"core","status":"active","repository":"https://use-cases.tasktide.org/ImageAnalysis","path":"/ImageAnalysis"}

'''


#####################################
#####################################
##
## 4). Mario AI Agent
##
######################################
######################################


# Define record
PASSKEY=$(cat ../.secret/passkey)
TIME_STAMP=$(date +%s%3N)
UUID=$(uuidgen)
REPO_NAME="Mario AI Agent"
REPO_URL="https://use-cases.tasktide.org/Mario-AI-Agent"

RECORD_PAYLOAD=$(jq -cn \
  --arg name "$REPO_NAME" \
  --arg description "Reinforcement Learning agent playing NES Mario Bros inside an isolated container environment whose workflow is Training and Playing and task set represents different worlds and levels of the NES Mario Bros game" \
  --arg type "core" \
  --arg status "active" \
  --arg repository "$REPO_URL" \
  --arg path "/Mario-AI-Agent" \
    '{
      name: $name,
      description: $description,
      type: $type,
      status: $status,
      repository: $repository,
      path: $path
    }'
)


# Generate reference md5sum, and signature
RECORD_HASH=$(echo "$TIME_STAMP - $UUID - $REPO_NAME - $RECORD_PAYLOAD" | md5sum - | awk '{print $1}')
RECORD_SIGNATURE=$(echo "$RECORD_HASH" | openssl dgst -sha384 -hmac "$PASSKEY" | awk '{ print $2 }')


# Import record
sqlite3 tasktide-use-case-registry.db <<EOF

.parameter set :uuid 				'$UUID'
.parameter set :repoUrl 			'$REPO_URL'
.parameter set :repoName 			'$REPO_NAME'
.parameter set :timestamp 			'$TIMESTEP'
.parameter set :recordHash			'$RECORD_HASH'
.parameter set :recordSignature		'$RECORD_SIGNATURE'
.parameter set :recordPayload		'$RECORD_PAYLOAD'

INSERT INTO use_cases (
	UUID, Repo_Url,
	Record_Name, Record_Created_At,
	Record_Hash, Record_Signature,
	Payload
)

VALUES (
	:uuid, :repoUrl,
	:repoName, :timestamp,
	:recordHash, :recordSignature,
	:recordPayload
);

EOF


# Fetch record
sqlite3 tasktide-use-case-registry.db <<EOF

.headers on
.separator "\t"
.parameter set :repoName	'$REPO_NAME'

SELECT * FROM use_cases WHERE Record_Name = :repoName;

EOF


'''

Id      UUID    Repo_Url        Record_Name     Record_Created_At       Record_Hash     Record_Signature        Payload
4       62173c23-4b1e-4bbe-80de-4ca4a07fdb65    https://use-cases.tasktide.org/Mario-AI-Agent   Mario AI Agent          a0f8291389fa7a5e3cac9ae9101b79d2 2524758dd8f5afc5f990e463bdaadfaee2aa715fee2deedb0f0710ced7c80f7b72548f625a5a1ef87477e5eb44dc9caa {"name":"Mario AI Agent","description":"Reinforcement Learning agent playing NES Mario Bros inside an isolated container environment whose workflow is Training and Playing and task set represents different worlds and levels of the NES Mario Bros game","type":"core","status":"active","repository":"https://use-cases.tasktide.org/Mario-AI-Agent","path":"/Mario-AI-Agent"}

'''



########################################
########################################
##
## 5). Update DB Hash & Signature
##
########################################
########################################


# Create hash
md5sum tasktide-use-case-registry.db > tasktide-use-case-registry.db.md5sum


# Create signature
HASH=$( awk '{ print $1 }' tasktide-use-case-registry.db.md5sum )

echo "$HASH" | openssl dgst -sha384 -hmac "$PASSKEY" | awk '{ print $2 }' > tasktide-use-case-registry.db.md5sum.sig



# Verify hash and signature
md5sum -c tasktide-use-case-registry.db.md5sum

REF_SIG=$( cat tasktide-use-case-registry.db.md5sum.sig )
QUERY_SIG=$(awk '{ print $1 }' tasktide-use-case-registry.db.md5sum | openssl dgst -sha384 -hmac "$PASSKEY" | awk '{ print $2 }' )

if [ $REF_SIG != $QUERY_SIG ]
then
	echo -e "Provided database not verified"
else
	echo -e "Provided database has been verified"
fi

'''

tasktide-use-case-registry.db: OK

'''